# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GrammyPlus' do
 pod 'NXOAuth2Client’,’~> 1.2.8'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GrammyPlus

  target 'GrammyPlusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GrammyPlusUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
